# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5bac09fabdb33d824478b59ab150863468322451df0d0ab36eb50db51b5388d5f4141d346f5342a016dd39d92487653006dcbd114c6a089171391586909fa28

test:
  secret_key_base: b4cc1436e7bedbb29ed199c6a01b0b2811d9ceb8dd7f4a9b3f2c3e7dc4b9c91fec0d76acd0300ac47e084b97145a4e7cb57bf59db9280500b58dc07bff4b850e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
